# ------------------------------------------------------
#dog Walkers
# -----------------------------------------------------------------------------
# application - This is the name of the application
#               when the application is loaded to google application engine
#               it can be viewed in the following internet address(URL):
#               http://dogwalkers02.appspot.com/
# -----------------------------------------------------------------------------
application: dogwalkers02
# -----------------------------------------
# the version of the application we create
# -----------------------------------------
version: 1
# -----------------------------------------
# programming language
# -----------------------------------------
runtime: python27
# -----------------------------------------
# python sub version
# -----------------------------------------
api_version: 1
# ---------------------------------------------------------------------
# threadsafe - to prevent collision between calls to the application
#              from different clients
# ---------------------------------------------------------------------
threadsafe: true
# ---------------------------------------------------------------------
# add a static directory /stylesheets- we will place all our css files inside it
# ---------------------------------------------------------------------
handlers:
- url: /stylesheets
  static_dir: stylesheets
# ---------------------------------------------------------------------
# handlers - define an application file for each URL we get
# ---------------------------------------------------------------------
- url: /.*
  script: main.app
# ---------------------------------------------------------------------
# libraries in use- jinja2 and MySQLdb(latest version)
# ---------------------------------------------------------------------
libraries:
- name: jinja2
  version: latest

- name: MySQLdb
  version: latest
